services:
  orderer.org1.b-s1.com:
    image: hyperledger/fabric-orderer:2.5.15
    container_name: orderer.org1.b-s1.com
    working_dir: /var/hyperledger/orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_LOCALMSPID=Org1OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
    networks:
      - b-s1
    volumes:
      - ./org1.b-s1.com/data/certificate-authority/organizations/ordererOrganizations/org1.b-s1.com/orderers/orderer.org1.b-s1.com/msp:/var/hyperledger/orderer/msp
      - ./org1.b-s1.com/data/certificate-authority/organizations/ordererOrganizations/org1.b-s1.com/orderers/orderer.org1.b-s1.com/tls:/var/hyperledger/orderer/tls
      - ./org1.b-s1.com/data/orderers/orderer/orderer:/var/hyperledger/production/orderer
