Capabilities:
  Application: &ApplicationCapabilities
    V2_5: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Channel: &ChannelCapabilities
    V2_0: true
Organizations:
  - &Org1Orderer
    Name: Org1Orderer
    ID: Org1OrdererMSP
    MSPDir: ./org1.b-s2.com/ordererOrganizations/org1.b-s2.com/msp
    OrdererEndpoints:
      - orderer.org1.b-s2.com:7050
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org1OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org1OrdererMSP.admin')"
  - &Org1
    Name: Org1
    ID: Org1MSP
    MSPDir: ./org1.b-s2.com/peerOrganizations/org1.b-s2.com/msp
    AnchorPeers:
      - Host: peer0.org1.b-s2.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org1MSP.peer')"
  - &Org2
    Name: Org2
    ID: Org2MSP
    MSPDir: ./org2.b-s2.com/peerOrganizations/org2.b-s2.com/msp
    AnchorPeers:
      - Host: peer0.org2.b-s2.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org2MSP.peer')"

  - &Org3
    Name: Org3
    ID: Org3MSP
    MSPDir: ./org3.b-s2.com/peerOrganizations/org3.b-s2.com/msp
    AnchorPeers:
      - Host: peer0.org3.b-s2.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org3MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org3MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org3MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org3MSP.peer')"

  - &Org4
    Name: Org4
    ID: Org4MSP
    MSPDir: ./org4.b-s2.com/peerOrganizations/org4.b-s2.com/msp
    AnchorPeers:
      - Host: peer0.org4.b-s2.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org4MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org4MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org4MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org4MSP.peer')"

  - &Org5
    Name: Org5
    ID: Org5MSP
    MSPDir: ./org5.b-s2.com/peerOrganizations/org5.b-s2.com/msp
    AnchorPeers:
      - Host: peer0.org5.b-s2.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org5MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org5MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org5MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org5MSP.peer')"

Orderer: &OrdererDefaults
  Addresses:
    - orderer.org1.b-s2.com:7050
  Capabilities:
    <<: *OrdererCapabilities
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Organizations:
    - *Org1Orderer
Application: &ApplicationDefaults
  Policies:
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *ApplicationCapabilities
  Organizations:
    - *Org1
    - *Org2
    - *Org3
    - *Org4
    - *Org5

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities
Profiles:
  DefaultProfile:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
      etcdraft:
        Consenters:
          - Host: orderer.org1.b-s2.com
            Port: 7050
            ClientTLSCert: ./org1.b-s2.com/ordererOrganizations/org1.b-s2.com/orderers/orderer.org1.b-s2.com/tls/server.crt
            ServerTLSCert: ./org1.b-s2.com/ordererOrganizations/org1.b-s2.com/orderers/orderer.org1.b-s2.com/tls/server.crt
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
      Capabilities:
        <<: *ApplicationCapabilities
